Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2023
Var
numeros : vetor[1..3] de inteiro
contador : inteiro

Inicio
para contador <- 1 ate 3 faca
  leia(numeros[contador])
  escreva(numeros[contador])
fimPara

escreval(numeros[3])

escreval(numeros[1] + numeros[2])

Fimalgoritmo